apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ansible_role_rhel8_cis
  title: Ansible Automation to Scan and Remediate RHEL8 Vulnarabilities
  language: ansible
  description: |
    This ansible role will scan and remediate CIS recommendations for RHEL
  annotations:
    github.com/project-slug: ibmc-hcc-sandbox/RHEL8-CIS
    backstage.io/techdocs-ref: dir:.
  tags:
    - ansible
    - cis

spec:
  type: service
  owner: platform-engineering-team
  lifecycle: production
